### PR TITLE
Add collection fetch failed

### PR DESCRIPTION
**Pull request by stevelacy**
- add collection fetch failed function

### CODE REVIEW

**Comment by contra** [comment]
It's up to the user to provide a collectionFetchFailed and a modelFetchFailed - if we throw an error we give the user no chance to handle it gracefully

**Comment by funkytek** [comment]
there needs to be a default error function that can be over-ridden; with no error handling things fail silently like hitting an endpoint that doesn't exist and there is no bubble up of the failure to parse the returned HTML body, which also makes items think it's not null

**Comment by contra** [comment]
@funktek I agree but this PR doesn't do that, it makes all errors throw and the behavior can't be overridden

**Comment by funkytek** [comment]
sure but it's better than nothing, let's throw a TODO in there with this

**Comment by contra** [comment]
fixed on master

**Pull request closed without merging**
