### PR TITLE
Allow a collection to be created from a model

### PR DESCRIPTION
**Pull request by stevelacy**
- adds support for a collection to be created from a model

### CODE REVIEW

**Comment by contra** [comment]
I think that this is more explicit though

```js
collectionView({
  collection: {
    model: User,
    otherOption: 123,
    otherOption: 123
  }
});
```

**Comment by funkytek** [comment]
I'm good with this but it doesn't currently work - can we prioritize this?

**Comment by contra** [comment]
Absolutely, but can you provide info on why it doesn't currently work?

**Comment by contra** [comment]
fixed on master

**Pull request closed without merging**
